


name: s3 Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    #environment: production

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: me-south-1

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
        

      - name: Install dependencies
        run: |
          npm install
          npm install -g @angular/cli


      - name: Build Website
        id: build-website
        run: |
          ng build
      
      - name: Deploy
        if: success()
        run: aws s3 sync ./dist/test-angular-appp s3://test-angular-appp


      #- name: Deploy
      #  if: success()
      #  uses: shallwefootball/s3-upload-action@master
      #  id: S3
      #  with:
      #    aws_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
      #    aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      #    aws_bucket: test-angular-appp
      #    source_dir: dist/angular6-httpclient/**/*